### ISSUE TITLE
Export CSV file name

### ISSUE THREAD

**Issue by jandersn** [walexnelson/pychampion#12]
Would like to have the file name include the db_refresh_date instead of today's date.

**Comment by walexnelson** [comment]
Take a look at the [custom context processors](https://github.com/walexnelson/pychampion/blob/dev/pychampion/pychampion/ct_processors.py). You should be able to use this same function to pull the db_refresh_date into your view.

**Comment by jandersn** [comment]
Thanks I think I got it working!
