### ISSUE TITLE
DB Sync Check DB_REFRESH_DATE

### ISSUE THREAD

**Issue by jandersn** [walexnelson/pychampion#6]
#TODO - add code to first check date last modified of finding track file before syncing DB
#If date last modified of file is <= user's current DB_REFRESH_DATE then Do not Sync
#display message box something like "Your DB is up to date" then prompt Sync anyway? 
#else sync

get DB_REFRESH_DATE
if DB_REFRESH_DATE >= datetime.today
then

**Comment by walexnelson** [comment]
Check out the refresh_db.html template. It already does this check and displays a different message as needed.

**Comment by jandersn** [comment]
Oh nice, I hadn't realized you already updated this. I see now you updated this 24 days ago. I was looking at the wrong file when I thought of this.
